### ISSUE TITLE
Motion Sensor data not updating

### ISSUE THREAD

**Issue by Aedge90** [Amos2016GroupOne/amos-ss16-proj1#75]
On Android 5.1.1, when I click on Show motion, the motion is displayed, but I get the following error in logcat:

```
06-04 17:00:13.080: I/SensorManagerFlow(25888): java.lang.Exception
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at android.hardware.SystemSensorManager.registerListenerImpl(SystemSensorManager.java:118)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at android.hardware.SensorManager.registerListener(SensorManager.java:775)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at android.hardware.SensorManager.registerListener(SensorManager.java:682)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at org.apache.cordova.devicemotion.AccelListener.start(AccelListener.java:157)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at org.apache.cordova.devicemotion.AccelListener.execute(AccelListener.java:107)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at org.apache.cordova.PluginManager.exec(PluginManager.java:133)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at android.os.Handler.dispatchMessage(Handler.java:102)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at android.os.Looper.loop(Looper.java:135)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at android.os.HandlerThread.run(HandlerThread.java:61)
```

Then I Hide the Motion and unhide it again. Then the values dont update anymore and I get the above error again. So I get the error everytime I unhide.

**Comment by Aedge90** [comment]
I posted a stackoverflow question about this, as I will probably never find the error myself ^^
http://stackoverflow.com/questions/37723740/cordova-plugin-device-motion-exception-in-start-method

**Comment by Aedge90** [comment]
Ok so this is "fixed". Seems to be a very specific problem, that only Honor 6 phones with android 5.1.1 installed have. I upgraded my phone to android 6 now and now it works fine
